### ISSUE TITLE
[Bug] Buttons on show not primary color

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/theme-tabler#173]
# Bug report

### What I did
I used tabs on show page. The buttons are blue insted of the primary color purple. 
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/20278289/eb7302d9-01a9-438c-84bc-adc695cd9871)

### What I expected to happen

Buttons pruple

### What I've already tried to fix it
Is related to this class but i don't know how or when is compiled

```css
.btn-link {
    color: #206bc4;
    background-color: transparent;
    border-color: transparent;
    box-shadow: none;
}
```

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

In the backpack demo in the show monster page
